---
configure_ssh: true
source_key: "./files/.ssh/id_rsa"
dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

configure_core: true
personal: "{{ lookup('env', 'HOME') }}/personal"
work: "{{ lookup('env', 'HOME') }}/work"

# Git Clone Repositories
configure_work: true
configure_personal: true

configure_dotfiles: false
configure_terminal: false

configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: 'Visual Studio Code'
#   path: '/Applications/Visual Studio Code.app/'
#   pos: 5

homebrew_installed_packages:
  #- { name: neovim, state: head, install_options: "override-system-vi" }
  - microsoft-teams
